# Generated by Django 6.0.4 on 2026-07-20 18:28

import core.encryption
import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimento', '0007_alter_atendimento_nextqs_fila'),
        ('core', '0018_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', core.encryption.EncryptedCharField(verbose_name='CPF')),
                ('cpf_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Hash do CPF')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('telefone', core.encryption.EncryptedCharField(blank=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('data_nascimento', core.encryption.EncryptedDateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('cargo', models.CharField(blank=True, max_length=120, verbose_name='Cargo')),
                ('empregador', models.CharField(blank=True, max_length=200, verbose_name='Empregador')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('origem', models.CharField(choices=[('RETROATIVO', 'Migração retroativa'), ('RECEPCAO', 'Recepção'), ('TRIAGEM_PUBLICA', 'Triagem pública'), ('MANUAL', 'Cadastro manual')], default='MANUAL', max_length=20, verbose_name='Origem do cadastro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associados_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Associado',
                'verbose_name_plural': 'Associados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TRABALHISTA', 'Trabalhista'), ('PREVIDENCIARIO', 'Previdenciário'), ('ANDAMENTO_PROCESSO', 'Andamento de Processo'), ('MEDICO', 'Médico do Trabalho'), ('DENUNCIA', 'Denúncia'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO_DOCUMENTOS', 'Aguardando documentos'), ('ENCERRADO', 'Encerrado'), ('ARQUIVADO', 'Arquivado')], default='ABERTO', max_length=25, verbose_name='Status')),
                ('dados_extra', models.JSONField(blank=True, default=dict, verbose_name='Dados adicionais')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('encerrado_em', models.DateTimeField(blank=True, null=True, verbose_name='Encerrado em')),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='associados.associado', verbose_name='Associado')),
                ('atendimentos', models.ManyToManyField(blank=True, related_name='casos', to='atendimento.atendimento', verbose_name='Atendimentos relacionados')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('departamento_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos', to='core.department', verbose_name='Departamento responsável')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CasoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DOCUMENTO_PESSOAL', 'Documento pessoal'), ('PROCURACAO', 'Procuração'), ('CONTRATO', 'Contrato'), ('COMPROVANTE', 'Comprovante'), ('EXAME', 'Exame/Laudo'), ('PROCESSO', 'Peça processual'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20, verbose_name='Tipo')),
                ('arquivo', models.FileField(upload_to='casos/%Y/%m/', validators=[core.validators.validate_file_extension, core.validators.validate_file_size], verbose_name='Arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome do arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='associados.caso', verbose_name='Caso')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Documento do caso',
                'verbose_name_plural': 'Documentos do caso',
                'ordering': ['created_at'],
            },
        ),
    ]
