# Generated by Django 6.0.4 on 2026-05-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_department_leader_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('MSG_SEND', 'Mensagem enviada'), ('MSG_DELETE', 'Mensagem apagada'), ('CARD_CREATE', 'Card criado'), ('CARD_UPDATE', 'Card atualizado'), ('CARD_DELETE', 'Card excluído'), ('USER_CREATE', 'Usuário criado'), ('USER_REGISTER', 'Cadastro solicitado'), ('USER_APPROVE', 'Usuário aprovado'), ('USER_REJECT', 'Usuário rejeitado'), ('USER_EDIT', 'Usuário editado'), ('USER_DEACTIVATE', 'Usuário desativado'), ('USER_ANONYMIZE', 'Usuário anonimizado'), ('DATA_EXPORT', 'Exportação de dados'), ('LGPD_CONSENT', 'Consentimento LGPD')], max_length=30, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('PRESIDENTE', 'Presidente'), ('ADMIN_TI', 'Administrador TI'), ('LIDER', 'Líder'), ('GERENTE', 'Gerente'), ('COLABORADOR', 'Colaborador')], default='COLABORADOR', max_length=20, verbose_name='Cargo'),
        ),
    ]
