# Generated by Django 6.0.4 on 2026-05-19 14:29

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=core.encryption.EncryptedDateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=core.encryption.EncryptedCharField(blank=True, verbose_name='Telefone'),
        ),
    ]
