# Generated by Django 6.0.4 on 2026-05-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_customuser_birth_date_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nextqs_agent_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Agent ID NextQS'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('CARD_ASSIGNED', 'Card atribuído a você'), ('CARD_DEPT', 'Card criado na sua área'), ('CARD_CROSS', 'Card entre departamentos'), ('CARD_COMMENT', 'Comentário em card'), ('CARD_MOVED', 'Card movido de coluna'), ('EVENT_INVITE', 'Convite para evento'), ('EVENT_REMINDER', 'Lembrete de evento')], max_length=20, verbose_name='Tipo'),
        ),
    ]
