# Generated by Django 6.0.4 on 2026-05-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_multi_dept_multi_leader_remove_gerente'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_post_comunicado',
            field=models.BooleanField(default=False, verbose_name='Pode criar comunicados'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('MSG_SEND', 'Mensagem enviada'), ('MSG_DELETE', 'Mensagem apagada'), ('CARD_CREATE', 'Card criado'), ('CARD_UPDATE', 'Card atualizado'), ('CARD_DELETE', 'Card excluído'), ('USER_CREATE', 'Usuário criado'), ('USER_REGISTER', 'Cadastro solicitado'), ('USER_APPROVE', 'Usuário aprovado'), ('USER_REJECT', 'Usuário rejeitado'), ('USER_EDIT', 'Usuário editado'), ('USER_DEACTIVATE', 'Usuário desativado'), ('USER_ANONYMIZE', 'Usuário anonimizado'), ('USER_PASSWORD_RESET', 'Senha redefinida'), ('DATA_EXPORT', 'Exportação de dados'), ('LGPD_CONSENT', 'Consentimento LGPD'), ('ATEND_CREATE', 'Atendimento criado'), ('ATEND_UPDATE', 'Atendimento atualizado'), ('ATEND_CLOSE', 'Atendimento concluído')], max_length=30, verbose_name='Ação'),
        ),
    ]
