# Generated by Django 6.0.4 on 2026-06-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_can_access_consultas'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_aprovador_diretoria',
            field=models.BooleanField(default=False, verbose_name='Aprova atividades de diretoria'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='valor_hora_diretoria',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Se vazio, usa o valor padrão do módulo Financeiro.', max_digits=8, null=True, verbose_name='Valor/hora diretoria'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('MSG_SEND', 'Mensagem enviada'), ('MSG_DELETE', 'Mensagem apagada'), ('CARD_CREATE', 'Card criado'), ('CARD_UPDATE', 'Card atualizado'), ('CARD_DELETE', 'Card excluído'), ('USER_CREATE', 'Usuário criado'), ('USER_REGISTER', 'Cadastro solicitado'), ('USER_APPROVE', 'Usuário aprovado'), ('USER_REJECT', 'Usuário rejeitado'), ('USER_EDIT', 'Usuário editado'), ('USER_DEACTIVATE', 'Usuário desativado'), ('USER_ANONYMIZE', 'Usuário anonimizado'), ('USER_PASSWORD_RESET', 'Senha redefinida'), ('DATA_EXPORT', 'Exportação de dados'), ('LGPD_CONSENT', 'Consentimento LGPD'), ('ATEND_CREATE', 'Atendimento criado'), ('ATEND_UPDATE', 'Atendimento atualizado'), ('ATEND_CLOSE', 'Atendimento concluído'), ('REEMB_CREATE', 'Reembolso solicitado'), ('REEMB_APPROVE', 'Reembolso aprovado'), ('REEMB_PAY', 'Reembolso pago'), ('REEMB_REJECT', 'Reembolso rejeitado'), ('DIRAT_CREATE', 'Atividade de diretoria criada'), ('DIRAT_APPROVE', 'Atividade de diretoria aprovada'), ('DIRAT_REJECT', 'Atividade de diretoria rejeitada'), ('DIRAT_PAY', 'Pagamento de diretoria realizado')], max_length=30, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('CARD_ASSIGNED', 'Card atribuído a você'), ('CARD_DEPT', 'Card criado na sua área'), ('CARD_CROSS', 'Card entre departamentos'), ('CARD_COMMENT', 'Comentário em card'), ('CARD_MOVED', 'Card movido de coluna'), ('EVENT_INVITE', 'Convite para evento'), ('EVENT_REMINDER', 'Lembrete de evento'), ('REEMBOLSO_NOVO', 'Novo reembolso para análise'), ('REEMBOLSO_STATUS', 'Atualização do seu reembolso'), ('DIRETORIA_NOVA', 'Nova atividade para aprovar'), ('DIRETORIA_STATUS', 'Atualização da sua atividade'), ('DIRETORIA_PAGO', 'Pagamento de diretoria realizado')], max_length=20, verbose_name='Tipo'),
        ),
    ]
