# Generated by Django 5.2.16 on 2026-08-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('MSG_SEND', 'Mensagem enviada'), ('MSG_DELETE', 'Mensagem apagada'), ('CARD_CREATE', 'Card criado'), ('CARD_UPDATE', 'Card atualizado'), ('CARD_DELETE', 'Card excluído'), ('USER_CREATE', 'Usuário criado'), ('USER_REGISTER', 'Cadastro solicitado'), ('USER_APPROVE', 'Usuário aprovado'), ('USER_REJECT', 'Usuário rejeitado'), ('USER_EDIT', 'Usuário editado'), ('USER_DEACTIVATE', 'Usuário desativado'), ('USER_ANONYMIZE', 'Usuário anonimizado'), ('USER_PASSWORD_RESET', 'Senha redefinida'), ('DATA_EXPORT', 'Exportação de dados'), ('LGPD_CONSENT', 'Consentimento LGPD'), ('ATEND_CREATE', 'Atendimento criado'), ('ATEND_UPDATE', 'Atendimento atualizado'), ('ATEND_CLOSE', 'Atendimento concluído'), ('TRIAGEM_SUBMIT', 'Triagem pública enviada'), ('TRIAGEM_FAIL', 'Triagem pública — tentativa inválida'), ('ASSOCIADO_VIEW', 'Ficha de associado consultada'), ('ASSOCIADO_EDIT', 'Ficha de associado editada'), ('CASO_CREATE', 'Caso criado'), ('CASO_UPDATE', 'Caso atualizado'), ('REEMB_CREATE', 'Reembolso solicitado'), ('REEMB_APPROVE', 'Reembolso aprovado'), ('REEMB_PAY', 'Reembolso pago'), ('REEMB_REJECT', 'Reembolso rejeitado'), ('DIRAT_CREATE', 'Atividade de diretoria criada'), ('DIRAT_APPROVE', 'Atividade de diretoria aprovada'), ('DIRAT_REJECT', 'Atividade de diretoria rejeitada'), ('DIRAT_PAY', 'Pagamento de diretoria realizado'), ('CHAMADO_CREATE', 'Chamado de TI aberto'), ('CHAMADO_UPDATE', 'Chamado de TI atualizado'), ('CHAMADO_CLOSE', 'Chamado de TI resolvido')], max_length=30, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('CARD_ASSIGNED', 'Card atribuído a você'), ('CARD_DEPT', 'Card criado na sua área'), ('CARD_CROSS', 'Card entre departamentos'), ('CARD_COMMENT', 'Comentário em card'), ('CARD_MOVED', 'Card movido de coluna'), ('EVENT_INVITE', 'Convite para evento'), ('EVENT_REMINDER', 'Lembrete de evento'), ('REEMBOLSO_NOVO', 'Novo reembolso para análise'), ('REEMBOLSO_STATUS', 'Atualização do seu reembolso'), ('DIRETORIA_NOVA', 'Nova atividade para aprovar'), ('DIRETORIA_STATUS', 'Atualização da sua atividade'), ('DIRETORIA_PAGO', 'Pagamento de diretoria realizado'), ('PROJETO_NOVO', 'Você foi incluído em um projeto'), ('PROJETO_FIM', 'Projeto finalizado'), ('PROJETO_MURAL', 'Nova mensagem no mural do projeto'), ('COMUNICADO_NOVO', 'Novo comunicado publicado'), ('CHAMADO_NOVO', 'Novo chamado de TI'), ('CHAMADO_ATRIB', 'Chamado atribuído a você'), ('CHAMADO_STATUS', 'Atualização do seu chamado'), ('CHAMADO_COMENT', 'Comentário no chamado')], max_length=20, verbose_name='Tipo'),
        ),
    ]
