# Generated by Django 6.0.4 on 2026-05-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Fixar')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
                'ordering': ['-is_pinned', '-published_at'],
            },
        ),
    ]
