# Generated by Django 6.0.4 on 2026-05-06 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunicados', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Deixe em branco para enviar a todos', to='core.department', verbose_name='Departamentos'),
        ),
    ]
