# Generated by Django 6.0.4 on 2026-06-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0003_comunicado_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Fixar no topo'),
        ),
    ]
