# Generated by Django 6.0.4 on 2026-07-08 20:41

from django.conf import settings
from django.db import migrations, models


def marcar_publicados_como_lidos(apps, schema_editor):
    """Evita explosão de badges: comunicados já publicados viram 'lidos' para
    todos os usuários existentes. Só notificações a partir daqui geram badge."""
    Comunicado = apps.get_model('comunicados', 'Comunicado')
    User = apps.get_model('core', 'CustomUser')
    users = list(User.objects.filter(is_active=True))
    if not users:
        return
    for c in Comunicado.objects.filter(is_published=True):
        c.read_by.add(*users)


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0004_alter_comunicado_is_pinned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='comunicados_lidos', to=settings.AUTH_USER_MODEL, verbose_name='Lido por'),
        ),
        migrations.RunPython(marcar_publicados_como_lidos, migrations.RunPython.noop),
    ]
