# Generated by Django 6.0.4 on 2026-06-03 18:06

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('arquivo', models.FileField(upload_to='agenda/%Y/%m/', validators=[core.validators.validate_file_extension, core.validators.validate_file_size], verbose_name='Arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome do arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_documentos', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='agenda.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['created_at'],
            },
        ),
    ]
