# Generated by Django 5.2.16 on 2026-08-12 12:56

import core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaTriagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200, verbose_name='Pergunta')),
                ('ajuda', models.CharField(blank=True, max_length=200, verbose_name='Texto de ajuda')),
                ('is_raiz', models.BooleanField(default=False, help_text='Marque apenas UMA pergunta como inicial (entrada do assistente).', verbose_name='É a pergunta inicial?')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Pergunta da triagem',
                'verbose_name_plural': 'Perguntas da triagem',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('icone', models.CharField(blank=True, max_length=10, verbose_name='Ícone')),
                ('prioridade_padrao', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10, verbose_name='Prioridade padrão')),
                ('sla_horas', models.PositiveIntegerField(blank=True, help_text='Prazo de atendimento em horas. Vazio = sem prazo.', null=True, verbose_name='SLA (horas)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('responsavel_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_chamado_padrao', to=settings.AUTH_USER_MODEL, verbose_name='Responsável padrão')),
            ],
            options={
                'verbose_name': 'Categoria de chamado',
                'verbose_name_plural': 'Categorias de chamado',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO', 'Aguardando solicitante'), ('RESOLVIDO', 'Resolvido'), ('FECHADO', 'Fechado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=15, verbose_name='Status')),
                ('respostas_triagem', models.JSONField(blank=True, default=list, verbose_name='Respostas da triagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Aberto em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('iniciado_em', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('resolvido_em', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados', to='chamados.categoriachamado', verbose_name='Categoria')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável (TI)')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_abertos', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChamadoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ABERTURA', 'Abertura'), ('COMENTARIO', 'Comentário'), ('ANDAMENTO', 'Andamento'), ('ATRIBUICAO', 'Atribuição'), ('STATUS', 'Mudança de status'), ('RESOLUCAO', 'Resolução'), ('REABERTURA', 'Reabertura'), ('CANCELAMENTO', 'Cancelamento')], max_length=15, verbose_name='Tipo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registrado em')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='chamados.chamado', verbose_name='Chamado')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChamadoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='chamados/%Y/%m/', validators=[core.validators.validate_file_extension, core.validators.validate_file_size], verbose_name='Arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome do arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='chamados.chamado', verbose_name='Chamado')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='chamados.chamadoetapa', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpcaoTriagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Resposta')),
                ('icone', models.CharField(blank=True, max_length=10, verbose_name='Ícone')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('prioridade', models.CharField(blank=True, choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], help_text='Opcional. Se preenchida, sobrepõe a prioridade padrão da categoria.', max_length=10, verbose_name='Prioridade')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opcoes_triagem', to='chamados.categoriachamado', verbose_name='Categoria final')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='chamados.perguntatriagem', verbose_name='Pergunta')),
                ('proxima_pergunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vem_de_opcoes', to='chamados.perguntatriagem', verbose_name='Próxima pergunta')),
            ],
            options={
                'verbose_name': 'Opção de resposta',
                'verbose_name_plural': 'Opções de resposta',
                'ordering': ['ordem', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('proxima_pergunta__isnull', False), ('categoria__isnull', True)), models.Q(('proxima_pergunta__isnull', True), ('categoria__isnull', False)), _connector='OR'), name='opcao_triagem_destino_xor')],
            },
        ),
    ]
