# Generated by Django 6.0.4 on 2026-05-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_card_source_subtask_subtaskanexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='source_atendimento_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do atendimento de origem'),
        ),
    ]
