# Generated by Django 6.0.4 on 2026-05-19 14:29

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_column_type_card_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtaskanexo',
            name='arquivo',
            field=models.FileField(upload_to='subtarefas/%Y/%m/', validators=[core.validators.validate_file_extension, core.validators.validate_file_size], verbose_name='Arquivo'),
        ),
    ]
