# Generated by Django 6.0.4 on 2026-05-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0008_cardanexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Concluído em'),
        ),
    ]
