# Generated by Django 6.0.4 on 2026-05-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0009_card_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento'),
        ),
    ]
