# Generated by Django 6.0.4 on 2026-06-30 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_customuser_is_aprovador_diretoria_and_more'),
        ('kanban', '0011_recurringtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
        migrations.CreateModel(
            name='BoardFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='Cor')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='Ícone')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folders', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_folders', to='core.department', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Pasta',
                'verbose_name_plural': 'Pastas',
                'ordering': ['order', 'name'],
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.AddField(
            model_name='board',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards', to='kanban.boardfolder', verbose_name='Pasta'),
        ),
    ]
