# Generated by Django 6.0.4 on 2026-06-30 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_notification_type'),
        ('kanban', '0012_alter_card_options_boardfolder_board_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em'),
        ),
        migrations.AddField(
            model_name='board',
            name='finished_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_boards', to=settings.AUTH_USER_MODEL, verbose_name='Finalizado por'),
        ),
        migrations.AddField(
            model_name='board',
            name='member_departments',
            field=models.ManyToManyField(blank=True, related_name='member_boards', to='core.department', verbose_name='Áreas com acesso'),
        ),
        migrations.AddField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('FINALIZADO', 'Finalizado')], default='ATIVO', max_length=12, verbose_name='Status'),
        ),
    ]
