# Generated by Django 6.0.4 on 2026-06-30 20:06

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0013_board_finished_at_board_finished_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PastaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='kanban/documentos/%Y/%m/', validators=[core.validators.validate_file_extension, core.validators.validate_file_size], verbose_name='Arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome do arquivo')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='kanban.board', verbose_name='Projeto')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='kanban.boardfolder', verbose_name='Pasta')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('folder__isnull', False), ('board__isnull', True)), models.Q(('folder__isnull', True), ('board__isnull', False)), _connector='OR'), name='documento_folder_xor_board')],
            },
        ),
        migrations.CreateModel(
            name='PastaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mural_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='kanban.board', verbose_name='Projeto')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='kanban.boardfolder', verbose_name='Pasta')),
            ],
            options={
                'verbose_name': 'Post do mural',
                'verbose_name_plural': 'Posts do mural',
                'ordering': ['created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('folder__isnull', False), ('board__isnull', True)), models.Q(('folder__isnull', True), ('board__isnull', False)), _connector='OR'), name='post_folder_xor_board')],
            },
        ),
    ]
