# Generated by Django 6.0.4 on 2026-07-03 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0014_pastadocumento_pastapost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='private_cards', to=settings.AUTH_USER_MODEL, verbose_name='Pessoas com acesso'),
        ),
        migrations.AddField(
            model_name='card',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Privado'),
        ),
    ]
