# Generated by Django 6.0.4 on 2026-07-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_doctorschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Profissional', 'verbose_name_plural': 'Profissionais'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_medico',
            field=models.BooleanField(default=True, help_text='Desmarque para atendentes (pré/pós, triagem).', verbose_name='É médico'),
        ),
    ]
