# Generated by Django 6.0.4 on 2026-06-16 04:51

import core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_hora_diretoria_padrao', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor/hora diretoria (padrão)')),
                ('teto_horas_mensal', models.DecimalField(decimal_places=2, default=Decimal('32'), max_digits=5, verbose_name='Teto de horas por mês')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parâmetro Financeiro',
                'verbose_name_plural': 'Parâmetros Financeiros',
            },
        ),
        migrations.CreateModel(
            name='PagamentoDiretoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Competência (mês)')),
                ('horas_totais', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Horas aprovadas')),
                ('horas_pagas', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Horas pagas (com teto)')),
                ('valor_hora', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor/hora aplicado')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor total (R$)')),
                ('pago_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Pago em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_diretoria', to=settings.AUTH_USER_MODEL, verbose_name='Diretor')),
                ('pago_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_diretoria_baixados', to=settings.AUTH_USER_MODEL, verbose_name='Pago por')),
            ],
            options={
                'verbose_name': 'Pagamento de Diretoria',
                'verbose_name_plural': 'Pagamentos de Diretoria',
                'ordering': ['-competencia', 'diretor'],
                'unique_together': {('diretor', 'competencia')},
            },
        ),
        migrations.CreateModel(
            name='AtividadeDiretoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atividade', models.DateField(verbose_name='Data da atividade')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título / evento')),
                ('descricao', models.TextField(verbose_name='O que foi feito')),
                ('horas', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Horas')),
                ('comprovante', models.FileField(upload_to='financeiro/diretoria/%Y/%m/', validators=[core.validators.validate_file_extension, core.validators.validate_file_size], verbose_name='Comprovação de presença')),
                ('competencia', models.DateField(editable=False, verbose_name='Competência (mês)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('PAGA', 'Paga')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('aprovado_em', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('motivo_rejeicao', models.TextField(blank=True, verbose_name='Motivo da rejeição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('diretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_diretoria', to=settings.AUTH_USER_MODEL, verbose_name='Diretor')),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to='financeiro.pagamentodiretoria', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'Atividade de Diretoria',
                'verbose_name_plural': 'Atividades de Diretoria',
                'ordering': ['-data_atividade', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('papel_assinado', models.FileField(upload_to='financeiro/reembolsos/%Y/%m/', validators=[core.validators.validate_file_extension, core.validators.validate_file_size], verbose_name='Papel assinado')),
                ('comprovante', models.FileField(upload_to='financeiro/reembolsos/%Y/%m/', validators=[core.validators.validate_file_extension, core.validators.validate_file_size], verbose_name='Comprovante de pagamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('PAGO', 'Pago'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('aprovado_em', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('pago_em', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('motivo_rejeicao', models.TextField(blank=True, verbose_name='Motivo da rejeição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reembolsos_aprovados', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('pago_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reembolsos_pagos', to=settings.AUTH_USER_MODEL, verbose_name='Pago por')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reembolsos', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Reembolso',
                'verbose_name_plural': 'Reembolsos',
                'ordering': ['-created_at'],
            },
        ),
    ]
