# Generated by Django 6.0.4 on 2026-06-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_departamento_financeiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reembolso',
            name='aprovado_em',
        ),
        migrations.RemoveField(
            model_name='reembolso',
            name='aprovado_por',
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando pagamento'), ('PAGO', 'Pago'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10, verbose_name='Status'),
        ),
    ]
