# Generated by Django 6.0.4 on 2026-06-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_remove_reembolso_aprovado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadediretoria',
            name='horas_aprovadas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Definido na aprovação. Pode ser menor que as horas lançadas (aprovação parcial).', max_digits=5, null=True, verbose_name='Horas aprovadas'),
        ),
    ]
