# Generated by Django 6.0.4 on 2026-06-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_atividadediretoria_horas_aprovadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadediretoria',
            name='motivo_ajuste',
            field=models.TextField(blank=True, help_text='Justificativa obrigatória quando aprova menos horas do que as lançadas.', verbose_name='Motivo do ajuste de horas'),
        ),
    ]
