# Generated by Django 6.0.4 on 2026-05-19 14:29

import core.encryption
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_atendimento_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='cpf_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Hash do CPF'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='cpf',
            field=core.encryption.EncryptedCharField(verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='telefone',
            field=core.encryption.EncryptedCharField(blank=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='atendimentoanexo',
            name='arquivo',
            field=models.FileField(upload_to='atendimentos/%Y/%m/', validators=[core.validators.validate_file_extension, core.validators.validate_file_size], verbose_name='Arquivo'),
        ),
    ]
