# Generated by Django 6.0.4 on 2026-05-25 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_atendimento_cpf_hash_alter_atendimento_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='is_retorno',
            field=models.BooleanField(default=False, verbose_name='É retorno?'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='nextqs_fila',
            field=models.CharField(blank=True, choices=[('J', 'Jurídico'), ('P', 'Previdenciário'), ('T', 'Trabalhista'), ('A', 'Andamento de Processo'), ('M', 'Médico do Trabalho')], max_length=1, verbose_name='Fila NextQS'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='numero_senha',
            field=models.CharField(blank=True, max_length=10, verbose_name='Nº Senha'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='retorno_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retornos', to='atendimento.atendimento', verbose_name='Retorno do atendimento'),
        ),
    ]
