# Generated by Django 6.0.4 on 2026-07-20 18:29

import core.encryption
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0001_initial'),
        ('atendimento', '0007_alter_atendimento_nextqs_fila'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='associado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='associados.associado', verbose_name='Associado'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='triagem_codigo',
            field=models.CharField(blank=True, db_index=True, max_length=8, verbose_name='Código curto da triagem'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='triagem_preenchida_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Triagem preenchida em'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='triagem_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Token da triagem'),
        ),
        migrations.CreateModel(
            name='TriagemPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('P', 'Previdenciário (aposentadoria, INSS, benefícios)'), ('T', 'Trabalhista (demissão, verbas, direitos)'), ('A', 'Andamento de processo já em curso'), ('M', 'Médico do Trabalho'), ('D', 'Denúncia'), ('O', 'Outro assunto')], max_length=1, verbose_name='Motivo')),
                ('descricao', models.TextField(verbose_name='Descrição do problema')),
                ('nome_informado', models.CharField(blank=True, max_length=200, verbose_name='Nome informado')),
                ('telefone', core.encryption.EncryptedCharField(blank=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('cargo', models.CharField(blank=True, max_length=120, verbose_name='Cargo')),
                ('empregador', models.CharField(blank=True, max_length=200, verbose_name='Empregador')),
                ('origem', models.CharField(choices=[('QR', 'QR code (celular)'), ('TOTEM', 'Totem da recepção')], default='QR', max_length=10, verbose_name='Origem')),
                ('lgpd_consent', models.BooleanField(default=False, verbose_name='Consentimento LGPD')),
                ('policy_version', models.CharField(default='1.0', max_length=20, verbose_name='Versão da política')),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do consentimento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triagem_publica', to='atendimento.atendimento', verbose_name='Atendimento')),
            ],
            options={
                'verbose_name': 'Triagem pública',
                'verbose_name_plural': 'Triagens públicas',
                'ordering': ['-created_at'],
            },
        ),
    ]
